title: 'xhable1337.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/site"
url: "https://xhable1337.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: '© <a href="mailto:evgeny@zgursky.tk">evgeny@zgursky.tk</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
